version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: covid/php
    container_name: covid_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./_docker/usr/local/etc/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - covid_network

  webserver:
    image: nginx:alpine
    container_name: covid_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./_docker/etc/nginx/conf.d/default.conf/:/etc/nginx/conf.d/default.conf
    networks:
      - covid_network

  db:
    image: mysql:5.7.22
    container_name: covid_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./_docker/var/lib/mysql:/var/lib/mysql
      - ./_docker/etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - covid_network

networks:
  covid_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
